### PR TITLE
Fixed Review Changes

### PR DESCRIPTION
**Pull request by Anamika-123**
- Fixed review changes of #2
- Fixed review changes of #14 
- Fixed review changes of #15 
- Fixed review changes of #16 
- Fixed review changes of #17

### CODE REVIEW

**Comment by karthiknmenon** [comment]
@Anamika-123 Why is yarn.lock included in this PR?

**Comment by Anamika-123** [comment]
@karthiknmenon It was by mistake.

**Comment by karthiknmenon** [comment]
@Anamika-123 Please revert the changes.

**Comment by Anamika-123** [comment]
@karthiknmenon Done.

**Review by karthiknmenon — APPROVED** [review]

**Pull request merged**
